import imageCard1 from "../assets/images/imageMessage.png";
import imageCard2 from "../assets/images/imageMessage2.png";
import imageCard3 from "../assets/images/imageMessage3.png";

export const dataMessage = [
  {
    id: 1,
    quote:
      "The place is nice with a village atmosphere surrounded by trees, really cool",
    name: "Phillip Press",
    role: "Traveler",
    avatar: imageCard1,
  },
  {
    id: 2,
    quote:
      "The rooms are okay, the breakfast is okay, new and traditional menus are added",
    name: "Tatiana Levin",
    role: "Travel Blogger",
    avatar: imageCard2,
  },
  {
    id: 3,
    quote:
      "strategic location, very pleasant at this villa. next time will come back again to spend the night here",
    name: "Kaiya Vaccaro",
    role: "Digital Nomads",
    avatar: imageCard3,
  },
];
